name: impulse_flutter
description: "Minimalist state management and dependency injection."
version: 0.4.0
repository: https://github.com/Yoeri-z/impulse
issue_tracker: https://github.com/Yoeri-z/impulse/issues
topics:
  - state
  - reactive
  - dependency-injection

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  impulse: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.5
