name: impulse_signals
description: "An integration of signals into the impulse_flutter package."
version: 0.4.0
homepage: https://github.com/Yoeri-z/impulse
issue_tracker: https://github.com/Yoeri-z/impulse/issues
topics:
  - state
  - signals

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  impulse_flutter: ^0.4.0
  signals_flutter: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.5

flutter:
